from pydantic import BaseModel, Field

class AddRoadRequest(BaseModel):
    common_info: str = Field(alias='common-info')
    road_owners: str = Field(alias='road-owners')
    operating_organizations: str = Field(alias='operating-organizations')
    regulations: str = Field(alias='regulations')
    backbone_network: str = Field(alias='backbone-network')
    start_exploraion: str = Field(alias='start-exploraion')
    paid_section_of_the_road: str = Field(alias='paid-section-of-the-road')
    dangerous_sections: str = Field(alias='dangerous-sections')
    cross_subjects: str = Field(alias='cross-subjects')
    climatic_zones: str = Field(alias='climatic-zones')
    terrain_types: str = Field(alias='terrain-types')
    max_speeds: str = Field(alias='max-speeds')
    axle_loads: str = Field(alias='axle-loads')
    traffic_intensities: str = Field(alias='traffic-intensities')
    categories: str = Field(alias='categories')
    road_class: str = Field(alias='road-class')
    number_of_lanes: str = Field(alias='number-of-lanes')
    roadway_width: str = Field(alias='roadway-width')
    earthen_canvas_width: str = Field(alias='earthen-canvas-width')
    type_of_coatings: str = Field(alias='type-of-coatings')
    geodata: str = Field(alias='geodata')
